# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

language: php

services:
  - mysql

dist: xenial

env:
  global:
    - COMPOSER_ROOT_VERSION=5.x-dev

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.4
      env: DB=MYSQL PHPUNIT_TEST=1

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:^4
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
